[tool.pytest.ini_options]
addopts = "-q --cov=src --cov-report=term-missing --cov-fail-under=80"
markers = [
  "integration: requires Docker and Postgres"
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E","F","I","B","UP","SIM","PL"]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
ignore_missing_imports = true
explicit_package_bases = true
allow_untyped_decorators = true
files = ["src/relml", "tools", "tests"]
