name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Lint & Format
        run: |
          ruff check .
          black --check .
          isort --check-only .
      - name: Typecheck
        run: mypy src tools tests
      - name: Tests
        run: pytest -q
